name: Test DPI Examples

on:
  push:
    paths-ignore:
      - README.md
  pull_request:
  workflow_dispatch:
    inputs:
      renode_url_linux:
        description: URL to a Linux portable Renode package
        required: true
        type: string
      renode_url_windows:
        description: URL to a Windows Renode package
        required: true
        type: string
      verilator_git_ref:
        description: Reference to a Verilator commit
        required: true
        type: string

jobs:
  build-verilator-linux:
    uses: ./.github/workflows/build-verilator.yml
    with:
      runner: ubuntu-20.04
      verilator_git_ref: ${{ inputs.verilator_git_ref || 'v5.010' }}
  build-verilator-windows:
    uses: ./.github/workflows/build-verilator.yml
    with:
      runner: windows-latest
      verilator_git_ref: ${{ inputs.verilator_git_ref || 'v5.010' }}


  run-sample:
    name: Run sample
    needs: [build-verilator-linux, build-verilator-windows]
    strategy:
      fail-fast: false
      matrix:
        sample:
          - directory_name: axi_ram
          - directory_name: axi_fastvdma
        config:
          - runner: ubuntu-20.04
            renode_url: ${{ inputs.renode_url_linux || 'https://builds.renode.io/renode-latest.linux-portable.tar.gz' }}
            verilator_artifact: ${{ needs.build-verilator-linux.outputs.verilator_artifact }}
          - runner: windows-latest
            renode_url: ${{ inputs.renode_url_windows || 'https://builds.renode.io/renode-latest.zip' }}
            verilator_artifact: ${{ needs.build-verilator-windows.outputs.verilator_artifact }}

    uses: ./.github/workflows/run-sample.yml
    with:
      sample: ${{ matrix.sample.directory_name }}
      custom_artifact: ${{ matrix.sample.custom_artifact || false }}
      custom_cmake_args: ${{ matrix.sample.custom_cmake_args || '' }}
      custom_robot_args: ${{ matrix.sample.custom_robot_args || '' }}

      runner: ${{ matrix.config.runner }}
      renode_url: ${{ matrix.config.renode_url }}
      verilator_artifact: ${{ matrix.config.verilator_artifact }}
